import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "SHT Lab",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="fr">
         <body
            className={cn(
               "flex flex-col min-h-screen w-full bg-white text-black",
               inter.className,
               {
                  "debug-screens": process.env.NODE_ENV === "development",
               }
            )}
         >
            {/* navbar */}
            <Navbar />
            {/* main page */}
            <div className="p-20 w-full">{children}</div>
         </body>
      </html>
   );
}
